timhul/ClassicSim

Class/Druid/Spells/Moonfire.cpp
`cooldown` was being deleted in both `Moonfire` and `SpellPeriodic` and
was attempting to delete a non-new'd pointer and was failing.
Thus, remote the line in `Moonfire` since `SpellPeriodic` properly owns
this.
=> Don't delete cooldown in Moonfire

Equipment/EquipmentDb/Shoulders/leather.xml
Many believe these are bis for hunters who are hit capped, so it would be nice to be able to sim them.
=> Add Wyrmtongue Shoulders

Spells/ExternalBuff.cpp
https://classic.wowhead.com/spell=15366/songflower-serenade Buff was missing the spell crit modifier.
=> Added 5% spellcrit to Songflower Serenade

Equipment/EquipmentDb/Gloves/leather.xml, Equipment/EquipmentDb/Gloves/plate.xml, Equipment/EquipmentDb/Legs/leather.xml, Equipment/EquipmentDb/Wrists/leather.xml, Equipment/EquipmentDb/set_bonuses.xml, QML/Assets/items/Inv_gauntlets_24.png, qml.qrc
Added missing shadowcraft pieces, icons, and implemented set bonus for shadowcraft and nightslayer.
I'm not sure if it's even possible to implement the special set effects as described so instead I implemented their calculated agility weight from https://shadowpanther.net/armor-sets.htm which I imagine is better than nothing.
=> added gear/set bonus for rogue pieces

Rotation/Rotations/Rogue/SealFateDagger.xml, Rotation/Rotations/rotation_paths.xml
This adds a pve rotation for the 3X/xx/5 variation of rogue builds that utilize seal fate.
=> Add a seal fate dagger rogue rotation

Equipment/EquipmentDb/Boots/leather.xml
It's available at phase 1 instead of 5.
=> Fix Cadaverous Walkers

Character/Character.cpp, Character/Character.h, Character/CharacterStats.cpp, Character/Race/Races/Gnome.cpp, Character/Race/Races/Human.cpp, Class/Druid/Druid.cpp, Class/Druid/Druid.h, Class/Hunter/Hunter.cpp, Class/Hunter/Hunter.h, Class/Mage/Mage.cpp, Class/Mage/Mage.h, Class/Paladin/Paladin.cpp, Class/Paladin/Paladin.h, Class/Priest/Priest.cpp, Class/Priest/Priest.h, Class/Rogue/Rogue.cpp, Class/Rogue/Rogue.h, Class/Shaman/Shaman.cpp, Class/Shaman/Shaman.h, Class/Warlock/Warlock.cpp, Class/Warlock/Warlock.h, Class/Warrior/Warrior.cpp, Class/Warrior/Warrior.h, GUI/GUIControl.cpp
Fix #42 and part 4 of #102 
Values are taken from https://classicwow.live/guides/46/basic-stats-sheet
I removed virtual methods from Character class since they are redundant with increase_xxx methods from CharacterStats.
7 special cases had to be added because there is no set of parameters to obtain all the basic statistics specified in the link above.
=> Fix basic stats for all characters

Class/Common/GeneralBuffs.cpp
Fixes #121 and allows ClassicSim to be built on Qt 5.14.
=> Add explicit constructor to avoid ambiguous function call

Class/Common/Buffs/SanctifiedOrb.cpp, Class/Common/Buffs/SanctifiedOrb.h, ClassicSim.pro, Equipment/EquipmentDb/Misc/trinkets.xml, Equipment/Item/Item.cpp, QML/Assets/items/Inv_misc_gem_pearl_04.png, QML/Assets/items/Inv_misc_ticket_tarot_maelstrom_01.png, Rotation/Rotations/Paladin/SealOfCommand.xml, Rotation/Rotations/Paladin/SealOfTheCrusader.xml, Test/Rotation/TestRotationFileReader.cpp, qml.qrc
Maelstrom's proc rate might be highly inaccurate and will need some adjustments once P3 hits. I couldn't really find any reliable information; in some comments on Wowhead it even says the proc rate depends on weapon speed (ppm). Seems like it wasn't always right on private servers either. 
As for the other commit, I hope I adjusted everything correctly. :)
=> Add Darkmoon Card: Maelstrom and Sanctified Orb

GUI/GUIControl.cpp, GUI/GUIControl.h, QML/Equipment.qml, QML/EquipmentTooltip.qml, QML/ItemEntry.qml, QML/ItemEntryWeapon.qml
=> Add a tooltip on mouseover in equipment tab

Equipment/SetBonusControl.cpp
Testing shows a bit more than 1%. See Zatar's explanation at https://youtu.be/e1e38Xl7Vs4?t=318
=> Update shadowcraft 6pc proc rate to 3.5%

Class/Warrior/Buffs/BattleStanceBuff.cpp, Class/Warrior/Buffs/BattleStanceBuff.h, Class/Warrior/Warrior.cpp, Class/Warrior/WarriorSpells.cpp, Class/Warrior/WarriorSpells.h, ClassicSim.pro
Currently this is a trivial no-op stance. However, in order to account
for threat modifiers in each stance we will need a stance to apply and
remove buffs (90% for battle/berserker and 150% for defensive).
=> Add BattleStanceBuff for Warriors

.clang-format
This project has some code style rules written in a doc on the github
repository. It's much easier for contributors to just run clang-format
on the project instead of going to a URL and reading to make sure things
are right.
As a first step, add the .clang-format the qt-creator github repository.
I modified a few configurations to make it agree with this project:
* I added a section that implements the include sorting rules.
* I set the columnLimit to 200. This project doesn't seem to have a hard
limit.
* I set `DerivePointerAlignment` which will try to figure out how the
file authors put the & in, e.g., `int & a` (right|left|middle).
There are pretty widespread inconsistencies with the pointer alignment
patterns. Other than that this .clang-format seems minimally invasive
for enforcing …
=> Add a .clang-format file

Character/CharacterStats.cpp, Character/CharacterStats.h, Character/Stats.cpp, Character/Stats.h
This simply stubs them out so that they are merely usable by other
classes. Proper implementation for items that boost it and shields will
have to follow.
=> Add Block Value to CharacterStats and Stats

Rotation/Rotations/Paladin/SealOfCommand.xml
Following #158, this improves paladin's DPS quite a bit, while still ensuring you don't run out of mana to keep SoC up. My goal is also to implement #60 eventually.
=> Make paladin rotation use judgement on cooldown

Equipment/EquipmentDb/Belts/cloth.xml, Equipment/EquipmentDb/Boots/cloth.xml, Equipment/EquipmentDb/Chests/cloth.xml, Equipment/EquipmentDb/Gloves/cloth.xml, Equipment/EquipmentDb/Helms/cloth.xml, Equipment/EquipmentDb/Legs/cloth.xml, Equipment/EquipmentDb/Shoulders/cloth.xml, Equipment/EquipmentDb/Wrists/cloth.xml, Equipment/Item/ItemStatsEnum.cpp
Part of https://github.com/timhul/ClassicSim/issues/167
I added the XML for all eight T2 Warlock items.
It seemed like HEALTH_PER_5 was missing an ItemStatsEnum entry. Added.
This is my first commit and I'm new to this. I haven't tested, whether it's actually working, since my dev environment for this project isn't setup (yet). This is mostly copy pasta from the corresponding Netherwind items, so it has a good chance of working. I have verified, that the assets (item graphics) actually exist.
=> Adding Warlock T2 Items

Thread/SimulationRunner.cpp, Thread/SimulationRunner.h, Thread/SimulationThreadPool.cpp
run_sim is a very overloaded term in this codebase around seven-ish
different versions existing across five-ish different classes. Given
that signals/slots require `grep`, we can rename this member func to
give it a unique name.
=> Rename SimRunner::run_sum to sim_runner_run

GUI/GUIControl.cpp
Qt5 implements cleaner syntax that doesn't use macros to setup connections. Start switching a few connections to use this mechanism.
=> Change some connections to use Qt5 syntax

Equipment/EquipmentDb/EquipmentDb.cpp
If the user makes a mistake setting up their build environment they might receive this error when running:
"The system cannot find the file specified."
But the error doesn't say which file it can't find.
=> better error msg when equipment_paths.xml missing

Equipment/EquipmentDb/Belts/leather.xml, Equipment/EquipmentDb/Boots/leather.xml, Equipment/EquipmentDb/Gloves/leather.xml, Equipment/EquipmentDb/Misc/backs.xml, Equipment/EquipmentDb/Misc/rings.xml, Equipment/EquipmentDb/Weapons/1hDaggers.xml
These are items available on the balance druid spreadsheet that are missing from ClassicSim.
- Waterspout Boots
- Crystalline Threaded Cape
- Mindfang
- Elemental Focus Band
- Band of the Inevitable
- Band of Servitude
- Rune Band of Wizardry
- Flayed Doomguard Belt
- Gloves of Earthen Power
=> Add items from moonkin spreadsheet

Thread/SimulationRunner.cpp, Thread/SimulationRunner.h, Thread/SimulationThreadPool.cpp
The only mechanism to find the connection for a signal is grep and
`result` has ~750 usages in this codebase. For simplicity, rename it to
a trivially grepable term.
=> Rename SimulationRunner::result to simulation_runner_has_result

QML/Assets/items/Inv_gauntlets_18.png, QML/Assets/items/Inv_jewelry_ring_53naxxramas.png, qml.qrc
Add missing assets:
- Band of the Inevitable: `Inv_jewelry_ring_53naxxramas.png`
- Gloves of Earthen Power: `Inv_gauntlets_18.png`
I created this bug in #261. Will make sure to test the icons in the future.
EDIT: I've confirmed images are working for all items added in #261 with this PR.
=> Missing images from #261

Character/Character.cpp, Character/Character.h, Class/Druid/Druid.cpp, Class/Druid/Druid.h, Class/Druid/Spells/BearForm.cpp, Class/Druid/Spells/CatForm.cpp, Class/Druid/Spells/MoonkinForm.cpp, Class/Druid/Spells/TigersFury.cpp, Rotation/Conditions/ConditionVariableBuiltin.cpp, Rotation/Conditions/ConditionVariableBuiltin.h, Rotation/Rotations/Druid/FeralPowershifting.xml, Test/Druid/Spells/TestCatForm.cpp, Test/Druid/Spells/TestFerociousBite.cpp, Test/Druid/Spells/TestMaul.cpp, Test/Druid/Spells/TestShred.cpp, Test/Druid/Spells/TestSwipe.cpp
- Shapeshifting cooldowns are on GCD (cancelform is not)
- Tiger's Fury is off GCD (TODO: Still missing its own CD but it's useless to cast it more than once within a second)
- Powershifting rotation does not leave cat form when GCD is not ready (prevents meleeing in caster form)
- New BuiltinVariable "time_remaining_gcd" used to prevent shapeshifting in rotations when powershifting is not possible (action not ready)
See #219
=> Druid fixes

DevTools/copy_to_dir.py
The other script is hard coded to @timhul's personal setup. Given numerous different build and app packaging models that should be supported, this type of script isn't scalable. So instead just let the user pick the dir
e.g. on Darwin with qmake
```
./DevTools/copy_to_dir.py build/ClassicSim.app/Contents/MacOS
```
e.g. on Darwin with cmake (currently only lives in an abandoned pull request, but I use it locally)
```
./DevTools/copy_to_dir.py build/Debug/bin
```
=> Add a general purpose script that copies all resources to the first arg

Rotation/Rotation.cpp
This doesn't really make sense to complain about. This warning will
show up when, for example, a rotation attempts to use an ability with a
buff but the player didn't choose that talent. This is perfectly fine
and the rotation should just move on. But this spams the log with this
error message.
=> Remove 'Could not find buff for' Warning

GUI/ClassicSimControl.cpp, GUI/ClassicSimControl.h
These methods have nothing to do with the GUI and are responsible for
settings specific to the simulation run. Simply rename them to make
more sense.
=> Rename `x_gui_settings` to `x_configuration`

Character/Character.cpp, Character/Character.h, Character/CharacterEncoder.cpp, Character/CharacterLoader.cpp, Character/CharacterLoader.h, CombatRoll/CombatRoll.cpp, CombatRoll/CombatRoll.h, Mechanics/Mechanics.cpp
This is a simple setup that adds a `is_tanking` value to `Character`
which is then used by CombatRoll and Mechanics to correctly calculate
parry rates. Now we need a GUI toggle for `is_tanking`.
=> Add a attacking_from_behind setup and have target parry use it

GUI/ClassicSimControl.cpp, GUI/ClassicSimControl.h, QML/main.qml
Add an elegant and majestic toggle for the new tank flag. This, at the moment, only toggles whether or not the player will be getting paried.
=> Add Parry for the GUI

Character/Character.cpp, Character/Character.h, Character/CharacterSpells.cpp, GUI/ClassicSimControl.cpp, GUI/Models/RotationModel.cpp, GUI/Models/RotationModel.h
Rotation is handled a bit weird here. We have 3 different toggleable
setups for talents, equipment and buffs. We save the rotation
information in the same fashion as the above trio, but it doens't realy
make sense to apply the rotation necessarily to any of the above three
things. So it lives separate. But adding three buttons to the GUI to
track rotations would be even clumsier than we currently have it.
So instead just save the last selected rotation to be loaded on the next
launch.
Also, this implementation is also pretty weird. The
`ClassicSimControl::set_character` method wipes the rotation database
each time it is called and rebuilds it from the rotation XML files. It
does this because the same `RotationModel` is used for each class and
thus needs to be reset while switching.
So …
=> Fix restoring last toggled rotation from save file
