timhul/ClassicSim

- Equipment/EquipmentDb/Weapons/2hSwords.xml
- QML/Assets/items/Inv_sword_14.png
- qml.qrc
I think the other PR is broken beyond repair. This time from a separate branch as it should've been from the start, with master rebased upon.
> Add Demonshear

- Class/Paladin/Paladin.cpp
Now this wasn't quite correct. :)
> Use correct stats weighting for Paladins

- Class/Common/Enchants/EnchantName.h
- Class/Common/Enchants/EnchantStatic.cpp
- Class/Druid/DruidEnchants.cpp
- Class/Hunter/HunterEnchants.cpp
- Class/Mage/MageEnchants.cpp
- Class/Paladin/PaladinEnchants.cpp
- Class/Shaman/ShamanEnchants.cpp
This PR adds enchant bracers - Greater Intellect as it is bis bracer enchant for many classes. All classes which have it as bis have it added as an option now.
> Added greater intellect enchant for bracers

- Equipment/EquipmentDb/Gloves/mail.xml
- Equipment/EquipmentDb/Weapons/1hAxes.xml
Add Trueaim Gauntlets
Add Bone Slicing Hatchet
> Add some hunter equipment

- Equipment/EquipmentDb/Wrists/plate.xml
> Move Berserker Bracers from phase 4 to phase 3

- Equipment/EquipmentDb/Chests/plate.xml
> Add Breastplate of Annihilation

- Statistics/ClassStatistics.h
> Fix unstable max DPS

- Equipment/EquipmentDb/Chests/leather.xml
- Equipment/EquipmentDb/Gloves/leather.xml
- Equipment/EquipmentDb/Legs/leather.xml
- Equipment/EquipmentDb/Shoulders/leather.xml
- Equipment/EquipmentDb/set_bonuses.xml
- Equipment/SetBonusControl.cpp
- QML/Assets/items/Inv_gauntlets_05.png
- qml.qrc
> Add Stormshroud Armor

- Equipment/EquipmentDb/Weapons/Ranged.xml
> Added a pre-raid BiS gun for rogues

- Class/Common/Enchants/EnchantName.h
- Faction/AvailableFactions.h
- GUI/Models/ItemModel.h
- GUI/Models/Statistics/BuffBreakdownModel.h
- GUI/Models/Statistics/EngineBreakdownModel.h
- GUI/Models/Statistics/MeleeDamageAvoidanceBreakdownModel.h
- GUI/Models/Statistics/MeleeDamageBreakdownModel.h
- GUI/Models/Statistics/ProcBreakdownModel.h
- GUI/Models/Statistics/ResourceBreakdownModel.h
- GUI/Models/Statistics/RotationExecutorBreakdownModel.h
- GUI/Models/Statistics/RotationExecutorListModel.h
- GUI/Models/Statistics/ScaleResultModel.h
- GUI/Models/WeaponModel.h
- GUI/SimOption.h
- Phases/ContentPhase.h
More details can be found here:
https://woboq.com/blog/q_enum.html
> Replace deprecated Q_ENUMS with Q_ENUM

- GUI/GUIControl.cpp
- GUI/GUIControl.h
- GUI/Models/ActiveItemStatFilterModel.cpp
- GUI/Models/BuffModel.cpp
- GUI/Models/DamageMetersModel.cpp
- GUI/Models/DebuffModel.cpp
- GUI/Models/ItemModel.cpp
- GUI/Models/ItemTypeFilterModel.cpp
- GUI/Models/RotationModel.cpp
- GUI/Models/SimScaleModel.cpp
- GUI/Models/Statistics/BuffBreakdownModel.cpp
- GUI/Models/Statistics/EngineBreakdownModel.cpp
- GUI/Models/Statistics/MeleeDamageAvoidanceBreakdownModel.cpp
- GUI/Models/Statistics/MeleeDamageBreakdownModel.cpp
- GUI/Models/Statistics/ProcBreakdownModel.cpp
- GUI/Models/Statistics/ResourceBreakdownModel.cpp
- GUI/Models/Statistics/RotationExecutorBreakdownModel.cpp
- GUI/Models/Statistics/RotationExecutorListModel.cpp
- GUI/Models/Statistics/ScaleResultModel.cpp
- GUI/Models/WeaponModel.cpp
- Thread/SimulationThreadPool.cpp
For readability purposes, it is best to use emit when calling a signal.
> Add missing emits

- Class/Hunter/Procs/ExposeWeaknessProc.cpp
This PR fixes the proc chance of expose weakness per [this issue](https://github.com/timhul/ClassicSim/issues/155).
> Fixed expose weakness proc chance

- Class/Warrior/Spells/DefensiveStance.cpp
- Class/Warrior/Spells/DefensiveStance.h
- Class/Warrior/WarriorSpells.cpp
- Class/Warrior/WarriorSpells.h
- ClassicSim.pro
The DefensiveStanceBuff wasn't triggering due to the missing skill
> Add DefensiveStance spell

- Class/Warrior/Spells/Bloodthirst.cpp
- Class/Warrior/Spells/DeathWish.cpp
These don't require battle/berserker stance.
> Remove Defensive stance restriction on Bloodthirst and DeathWish

- Class/Warrior/Spells/SunderArmor.cpp
Just look at the second commit. This is to demonstrate the application of innate threat. Further breakdown of the hit/crit etc could also be added, but this is to just get it started.
> Apply Sunder Armor's innate threat

- Class/Warrior/Spells/ShieldSlam.cpp
- Class/Warrior/Spells/ShieldSlam.h
- Class/Warrior/TalentTrees/Protection.cpp
- Class/Warrior/TalentTrees/Protection.h
- Class/Warrior/WarriorSpells.cpp
- Class/Warrior/WarriorSpells.h
- ClassicSim.pro
> Implement Shield Slam

- GUI/SimControl.cpp
- Spells/ExternalBuff.cpp
This fixes Issues #222 and #221
> Fix Elixir of the Mongoose and Scale Factors

- Class/Common/Enchants/EnchantName.h
- Class/Common/Enchants/EnchantStatic.cpp
- Class/Druid/DruidEnchants.cpp
- Class/Hunter/HunterEnchants.cpp
- Class/Paladin/PaladinEnchants.cpp
- Class/Rogue/RogueEnchants.cpp
- Class/Shaman/ShamanEnchants.cpp
- Class/Warrior/WarriorEnchants.cpp
Its useful to be able to calculate with the cheaper enchants to assess the value of choosing the expensive ones.
> Add affordable boots and bracers enchants

- Equipment/EquipmentDb/Gloves/plate.xml
added item that was supposed to be added in Phase 6 but is already added to the game
> added Sacrificial Gauntlets from Zul'Gurub

- Equipment/EquipmentDb/Gloves/leather.xml
- Equipment/EquipmentDb/Legs/leather.xml
- QML/Assets/items/Inv_pants_leather_05.png
> Add Shadow Panther Hide Gloves and Abyssal Leather Leggings of Striking

- GUI/SimControl.cpp
> Replace random_shuffle with shuffle and a random_device

- Class/Common/GeneralBuffs.cpp
- QML/Assets/spell/Spell_holy_divinespirit.png
- Spells/ExternalBuff.cpp
- Spells/ExternalBuff.h
- qml.qrc
Adressing part of issue #102 + Divine Spirit buff
> Implement Arcane intellect and Divine Spirit as external buffs

- Equipment/EquipmentDb/Belts/cloth.xml
- Equipment/EquipmentDb/Misc/offhands.xml
- Equipment/EquipmentDb/Shoulders/cloth.xml
- Equipment/EquipmentDb/Wrists/cloth.xml
Phase change for abyssal items and Glowing Black Orb.
> Change abyssal items and Glowing Black Orb to phase 4

- GUI/GUIControl.cpp
- GUI/GUIControl.h
- QML/main.qml
Show the TPS result and the change of the TPS result above the DPS value in the top right corner.
> Show TPS in top right corner

- Equipment/Equipment.cpp
- Equipment/Equipment.h
Affixes were lost when changing gear sets, because they were not saved during the change.
This fixes issue #244
> Fix item affix not saved

- GUI/ClassicSimControl.cpp
- GUI/ClassicSimControl.h
- GUI/GUIControl.cpp
- GUI/GUIControl.h
Move some item selection related methods to GUIControl from CSControl
> Move some item selection related methods to GUIControl from CSControl

- GUI/ClassicSimControl.cpp
> Add missing class change signal

- Equipment/EquipmentDb/Belts/leather.xml
- Equipment/EquipmentDb/Boots/leather.xml
- Equipment/EquipmentDb/Chests/leather.xml
- Equipment/EquipmentDb/Gloves/leather.xml
- Equipment/EquipmentDb/Helms/leather.xml
- Equipment/EquipmentDb/Legs/leather.xml
- Equipment/EquipmentDb/Shoulders/leather.xml
- Equipment/EquipmentDb/Wrists/leather.xml
- Equipment/EquipmentDb/set_bonuses.xml
- Equipment/SetBonusControl.cpp
- Rotation/Rotations/Rogue/SealFateEA.xml
Just copied shadowcraft proc code to darkmantle proc code and updated the gear files. Used item levels off of classic.wowhead.com, may be off on those. Darkmantle Tunic says ilvl 60, I think it should be higher though. Double check for typos! On linux and can't compile.
> Added Darkmantle, basically shuffled up Shadowcraft

- Class/Common/Buffs/CharmOfTrickery.cpp
- Class/Common/Buffs/CharmOfTrickery.h
- ClassicSim.pro
- Equipment/EquipmentDb/Misc/neck.xml
- Equipment/EquipmentDb/Misc/trinkets.xml
- Equipment/EquipmentDb/Weapons/1hDaggers.xml
- Equipment/EquipmentDb/Wrists/leather.xml
- Equipment/EquipmentDb/set_bonuses.xml
- Equipment/Item/Item.cpp
- Rotation/Rotations/Rogue/Combat.xml
- Rotation/Rotations/Rogue/CombatDagger.xml
- Rotation/Rotations/Rogue/Hemorrhage.xml
- Rotation/Rotations/Rogue/SealFateDagger.xml
- Rotation/Rotations/Rogue/SealFateEA.xml
> Add multiple rogue items

- Class/Common/Enchants/EnchantName.cpp
> Fix Minor Agility enchant

- Equipment/EquipmentDb/Wrists/leather.xml
> Fix faulty XML tag

- Character/CharacterStats.cpp
- Character/CharacterStats.h
- Character/Stats.cpp
- Character/Stats.h
- Equipment/Equipment.cpp
- Equipment/Equipment.h
- Equipment/EquipmentDb/Misc/offhands.xml
- Equipment/EquipmentDb/Weapons/1hMaces.xml
- Equipment/Item/Item.cpp
- Equipment/Item/ItemStatsEnum.h
- QML/Assets/items/inv_misc_book_05.png
- Rotation/Conditions/ConditionVariableBuiltin.cpp
- qml.qrc
Preparations to include feral maces (e.g. from the Regalia quest reward)
> Add Feral AP

- Equipment/EquipmentDb/Weapons/Ranged.xml
> Fix Soulstring DPS

- Equipment/EquipmentDb/Gloves/cloth.xml
- QML/Assets/items/Inv_gauntlets_03.png
- qml.qrc
Added Item "Gloves of the Hypnotic Flame" and its Icon
(Information obtained from wowhead)
> Add Gloves of the Hypnotic Flame for fire mage

- Equipment/EquipmentDb/Boots/leather.xml
- Equipment/EquipmentDb/Chests/leather.xml
- Equipment/EquipmentDb/Gloves/leather.xml
- Equipment/EquipmentDb/Helms/leather.xml
- Equipment/EquipmentDb/Legs/leather.xml
- Equipment/EquipmentDb/Shoulders/leather.xml
- Equipment/EquipmentDb/set_bonuses.xml
- Add Druid PvP Epic Class Set for Horde
> Add Druid PvP R12/R13 Class Set for Horde
